<Megger_Test_Screen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

        GridLayout:
            cols: 2
            rows: 1
            spacing: 10
            size_hint_y: None
            height: 100
            TextInput:
                id: customer_name
                text: ''
                hint_text: 'Enter Customers Name' 
                multiline: False 
                size_hint_x: 1.5
                padding_x: 10  
                padding_y: 5
            Button:
                text: 'X'
                padding_x: 10  
                padding_y: 5
                size_hint_x: None
                on_press: 
                    root.clear_megger_spec(self)
                
        
        GridLayout:
            cols: 4
            rows: 4
            spacing: 5
            padding: 5
            size_hint_y: None
            height: 400
            
            CheckBox:
                id: underground_wire
            Label:
                text: 'Underground Wire'
                font_size: 40
                
            CheckBox:
                id: tower_disconnect_switch
            Label:
                text: 'Tower Disconnect\n Switch'
                font_size: 40
                
            CheckBox:
                id: tower_wire
            Label:
                text: 'Tower Wire'
                font_size: 40
                
            CheckBox:
                id: junction_box
            Label:
                text: 'Junction Box'
                font_size: 40
                
            CheckBox:
                id: slip_rings
            Label:
                text: 'Slip Rings'
                font_size: 40
                
            CheckBox:
                id: brush_block
            Label:
                text: 'Brush Block'
                font_size: 40
                
            CheckBox:
                id: altenator
            Label:
                text: 'Altenator'
                font_size: 40
                
            Label:
                size_hint_x: None
                text: ''
            Button:
                text: 'X '
                on_press: 
                    root.clear_megger_spec(self)

  
        GridLayout:
            cols:2
            rows:3
            size_hint_y: None
            height: 320
            spacing: 10
            TextInput:
                text: ''
                id: phase_1
                hint_text: 'Enter Phase 1'
                size_hint_y: None
                size_hint_x: 0.75
                height: 100
                padding_x: 10  
                padding_y: 5 
                multiline: False 
                input_filter: 'int' 

            Button:
                text: ' X '
                size_hint_y: None
                size_hint_x: None
                height: 100
                padding_x: 10  
                padding_y: 5 
                on_press: 
                    root.clear_megger_spec(self)
            
            TextInput:
                text: ''
                id: phase_2
                hint_text: 'Enter Phase 2'
                size_hint_y: None
                size_hint_x: 0.75
                height: 100 
                padding_x: 10  
                padding_y: 5 
                multiline: False 
                input_filter: 'int'

            Button:
                text: ' X  '
                size_hint_y: None
                size_hint_x: None
                height: 100
                padding_x: 10  
                padding_y: 5 
                on_press: 
                    root.clear_megger_spec(self)
            
            TextInput:
                text: ''
                id: phase_3
                hint_text: 'Enter Phase 3'
                size_hint_y: None
                size_hint_x: 0.75
                height: 100
                padding_x: 10  
                padding_y: 5 
                multiline: False 
                input_filter: 'int'

            Button:
                text: '  X  '
                size_hint_y: None
                size_hint_x: None
                height: 100
                padding_x: 10  
                padding_y: 5 
                on_press: 
                    root.clear_megger_spec(self)
        

        GridLayout:
            cols: 2
            rows: 1
            spacing: 10
            size_hint_y: None
            height: 100 
            
            Button:
                text: 'Enter'
                on_press: 
                    root.process_input()

            Button:
                text: 'Clear'
                on_press:
                    root.clear_inputs()

        Label: 
            id: megger_test_id
            font_size: 40
            text: ''
        GridLayout:
            cols: 1
            rows: 1
            spacing: 10
            size_hint_y: None
            height: 150 
            Button:
                text: 'To Main Screen'
                on_press:
                    root.manager.transition.direction='right'
                    root.manager.current = 'main_screen'
